### ISSUE TITLE
启动运行时报错

### ISSUE THREAD

**Issue by chenxikry** [h5ds/h5ds-bugs#6]
ERROR in ./src/app.js
Module build failed: Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Administrator.USER-20180705RP\node_modules\b
abel-loader\lib\index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Adminis
trator.USER-20180705RP\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at loadLoader (C:\Users\Administrator.USER-20180705RP\node_modules\loader-ru
nner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\Administrator.USER-20180705RP\node_modul
es\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\Administrator.USER-20180705RP\node_modules\loader-ru
nner\lib\LoaderRunner.js:362:2)
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8787 webpack/hot/dev-serve
r webpack-dev-server/client?http://127.0.0.1:8787 webpack/hot/only-dev-server ./
src/app.js
Child html-webpack-plugin for "index.html":

**Comment by hstarorg** [comment]
Please clear your `node_modules` folder and execute `npm i` again.

**Comment by hstarorg** [comment]
Long time no response, close it. If you reproduce the question, please open it again.
